# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftProject
pod 'RxSwift'
pod 'RxCocoa'

  target 'RxSwiftProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
