# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RXSwiftApiTableViewProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RXSwiftApiTableViewProject
pod 'RxSwift'
pod 'RxCocoa'

  target 'RXSwiftApiTableViewProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
