# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdMobProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdMobProject
pod 'Google-Mobile-Ads-SDK'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Database'
end
