# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BDDUnitTesting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BDDUnitTesting

  target 'BDDUnitTestingTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
